# Root
substitutions:
  board_name: root-energy-meter
  friendly_name: Root Energy Meter

# This board is the closest to what the original is.
# Actual board type is WT8266-S2.
# For reference: http://docs.hekr.me/v4/%E7%A1%AC%E4%BB%B6%E5%BC%80%E5%8F%91/%E6%B0%A6%E6%B0%AA%E6%A8%A1%>
esp8266:
  board: esp_wroom_02
  restore_from_flash: true

# Load external components
external_components:
  - source:
      type: git
      url: https://github.com/alryaz/esphome-components
      ref: main
    components: [ hekr ]
    refresh: 1s

# Disabling UART logging by default
logger:
  baud_rate: 0
  level: INFO

web_server:
  port: 80

# Configuration of the UART bus for 9600 baud rate
uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

hekr:

api:
  password: !secret root_energy_meter_api_password
  encryption:
    key: !secret root_energy_meter_api_encryption

ota:
  password: !secret root_energy_meter_ota_password

# Cause timed updates
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: /5
        then:
          hekr.command: 0
      - seconds: 0
        minutes: /1
        then:
          hekr.command: 10


packages:
  base: !include packages/base.yaml

switch:
  - platform: hekr
    name: "${friendly_name}"
    icon: "mdi:meter-electric"
    command: 1
    position: 1
    command_on: [0x09, 0x01]
    command_off: [0x09, 0x00]
    value_on: 0x01
    value_off: 0x00
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

button:
  - platform: template
    name: "${friendly_name} Query Basic Info"
    id: button_query_device
    icon: "mdi:refresh"
    on_press:
      then:
        hekr.command: 0
  - platform: template
    name: "${friendly_name} Query Settings"
    id: button_query_settings
    entity_category: diagnostic
    icon: "mdi:refresh"
    on_press:
      then:
        hekr.command: 2
  - platform: template
    name: "${friendly_name} Clear Device"
    id: button_clear_device
    entity_category: config
    icon: "mdi:trash-can"
    on_press: 
      then:
        hekr.command: 5
  - platform: template
    name: "${friendly_name} Query Meter ID"
    id: button_query_meter_id
    entity_category: diagnostic
    icon: "mdi:barcode"
    on_press:
      then:
        hekr.command: 2
  - platform: template
    name: "${friendly_name} Query Extended Info"
    id: button_query_extended_info
    entity_category: diagnostic
    icon: "mdi:refresh"
    on_press:
      then:
        hekr.command: 10

sensor:
  - platform: hekr
    name: "${friendly_name} Total Energy"
    id: sensor_total_energy
    command: 1
    position: 2
    length: 4
    filters:
      - multiply: 0.01
    icon: "mdi:sigma"
    accuracy_decimals: 2
    state_class: total
    device_class: energy
    unit_of_measurement: "kWh"
  
  - platform: hekr
    name: "${friendly_name} Reactive Power"
    id: sensor_reactive_power
    command: 11
    position: 15
    length: 3
    filters: &power_filters
      - lambda: &to_signed_float_filter "return x < 100000 ? x : 100000 - x;"
      - multiply: 0.1
    icon: "mdi:alpha-q"
    accuracy_decimals: 1
    state_class: measurement
    device_class: reactive_power
    unit_of_measurement: var

  - platform: hekr
    name: "${friendly_name} Active Power"
    id: sensor_active_power
    # command: 11
    # position: 27
    command: 1
    position: 7
    length: 3
    filters: *power_filters
    icon: "mdi:alpha-p"
    accuracy_decimals: 1
    state_class: measurement
    device_class: power
    unit_of_measurement: "W"

  - platform: hekr
    name: "${friendly_name} Power Factor"
    id: sensor_power_factor
    command: 11
    position: 39
    length: 2
    filters:
      - lambda: *to_signed_float_filter
      - multiply: 0.001
    icon: "mdi:math-cos"
    accuracy_decimals: 3
    state_class: measurement
    device_class: power_factor

  - platform: hekr
    name: "${friendly_name} Frequency"
    id: sensor_frequency
    command: 11
    position: 47
    length: 2
    filters:
      - multiply: 0.01
    icon: "mdi:sine-wave"
    accuracy_decimals: 2
    state_class: measurement
    device_class: frequency
    unit_of_measurement: "Hz"

  - platform: hekr
    name: "${friendly_name} Active Energy Import"
    id: sensor_active_energy_import
    command: 11
    position: 53
    length: 4
    filters:
      - multiply: 0.01
    icon: "mdi:transmission-tower-import"
    accuracy_decimals: 2
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh

  - platform: hekr
    name: "${friendly_name} Active Energy Export"
    id: sensor_active_energy_export
    command: 11
    position: 57
    length: 4
    filters:
      - multiply: 0.01
    icon: "mdi:transmission-tower-export"
    accuracy_decimals: 2
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh

  - platform: hekr
    name: "${friendly_name} Current"
    id: sensor_current
    command: 11
    position: 0
    length: 3
    filters:
      - multiply: 0.001
    icon: "mdi:alpha-i"
    accuracy_decimals: 3
    state_class: "measurement"
    device_class: "current"

    unit_of_measurement: "A"
  - platform: hekr
    name: "${friendly_name} Voltage"
    id: sensor_voltage
    command: 11
    position: 9
    length: 2
    filters:
      - multiply: 0.1
    icon: "mdi:alpha-v"
    accuracy_decimals: 1
    state_class: "measurement"
    device_class: "voltage"
    unit_of_measurement: "V"root-energy-meter
    friendly_name: Root Energy Meter
  
  # This board is the closest to what the original is.
  # Actual board type is WT8266-S2.
  # For reference: http://docs.hekr.me/v4/%E7%A1%AC%E4%BB%B6%E5%BC%80%E5%8F%91/%E6%B0%A6%E6%B0%AA%E6%A8%A1%>
  esp8266:
    board: esp_wroom_02
    restore_from_flash: true
  
  # Load external components
  external_components:
    - source:
        type: git
        url: https://github.com/alryaz/esphome-components
        ref: main
      components: [ hekr ]
      refresh: 1s
  
  # Disabling UART logging by default
  logger:
    baud_rate: 0
    level: INFO
  
  web_server:
    port: 80
  
  # Configuration of the UART bus for 9600 baud rate
  uart:
    id: uart_bus
    tx_pin: TX
    rx_pin: RX
    baud_rate: 9600
  
  hekr:
  
  api:
    password: !secret root_energy_meter_api_password
    encryption:
      key: !secret root_energy_meter_api_encryption
  
  ota:
    password: !secret root_energy_meter_ota_password
  
  time:
    - platform: homeassistant
      id: homeassistant_time
      on_time:
        - seconds: /5
          then:
            hekr.command: 0
        - seconds: 0
          minutes: /1
          then:
            hekr.command: 10
  
  
  packages:
    base: !include packages/base.yaml
  
  switch:
    - platform: hekr
      name: "${friendly_name}"
      icon: "mdi:meter-electric"
      command: 1
      position: 1
      command_on: [0x09, 0x01]
      command_off: [0x09, 0x00]
      value_on: 0x01
      value_off: 0x00
      optimistic: true
      restore_mode: RESTORE_DEFAULT_ON
  
  button:
    - platform: template
      name: "${friendly_name} Query Basic Info"
      id: button_query_device
      entity_category: diagnostic
      icon: "mdi:refresh"
      on_press:
        then:
          hekr.command: 0
    - platform: template
      name: "${friendly_name} Query Settings"
      id: button_query_settings
      entity_category: diagnostic
      icon: "mdi:refresh"
      on_press:
        then:
          hekr.command: 2
    - platform: template
      name: "${friendly_name} Clear Device"
      id: button