esphome:
  name: "${board_name}"
  comment: "Hekr Power Meter"
  project:
    name: "hekr.power_meter"
    version: "0.0.1"

# This board is the closest to what the original is.
# Actual board type is WT8266-S2.
# For reference: http://docs.hekr.me/v4/%E7%A1%AC%E4%BB%B6%E5%BC%80%E5%8F%91/%E6%B0%A6%E6%B0%AA%E6%A8%A1%E5%9D%97/WT8266-S2/
esp8266:
  board: esp_wroom_02
  restore_from_flash: true

# Load external components
external_components:
  - source:
      type: git
      url: https://github.com/alryaz/esphome-components
      ref: main
    components: [ hekr ]
    refresh: 1s

# Disabling UART logging by default
logger:
  baud_rate: 0

# Configuration of the UART bus for 9600 baud rate
uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600

# >>> Magic happens here <<<
hekr: