#############################
# Generic ESPHome preamable #
#############################

# Base platform setup
esphome:
  name: sonoff_d1_dimmer
  platform: ESP8266
  board: esp01_1m

# Enable Home Assistant API
api:

# Enable Over-the-Air updates
ota:

# Enable access point mode
wifi:
  ap:
    ssid: "Test Hotspot for Sonoff D1"
    password: "testhotspot"

# Redirect AP clients to device Home Page
captive_portal:

# Enable web server (for debugging)
web_server:
  port: 80

####################################
# Component-specific configuration #
####################################

# Enable logging, but disable it over serial; otherwise,
# serial communication with the dimmer part of the
# assembly will be impossible.
logger:
  baud_rate: 0

# Add repository with this component
external_components:
  - source:
      type: git
      url: https://github.com/alryaz/esphome-components
      ref: main
    components: [ sonoff_d1 ]

# UART must be set to 19200 baud rate (required by Nuvoton chip)
uart:
  baud_rate: 9600
  tx_pin: TX  # GPIO1 pin
  rx_pin: RX  # GPIO3 pin

light:
    # Create test light
  - platform: sonoff_d1
    name: "Sonoff D1 Dimmer"
    
    # Status LED (optional, located on GPIO13 for my test device)
  - platform: status_led
    name: "Status LED"
    id: status_led_1
    pin:
      number: GPIO13
      inverted: true